import React, { useState } from "react";
import GitHubIcon from "@mui/icons-material/GitHub";
import LinkedInIcon from "@mui/icons-material/LinkedIn";
import { IconButton } from "@mui/material";
import styles from "./Home.module.css";
import engineerArt from "../../assets/backend-ai-engineer.png";
import resumePdf from "../../assets/AdithyanKP_RESUME_2026.pdf";

const experience = [
  { role: "Software Engineer", company: "NeoITO", location: "Kochi, India", timeframe: "Jul 2022 — Present", bullets: ["Built a configurable low-code workflow platform with reusable nodes for Meta Cloud API, Google Sheets, webhooks, and REST integrations.", "Used RabbitMQ for asynchronous execution, scheduling, and event orchestration across 300+ businesses and 10,000+ daily customer interactions.", "Reduced publish-workflow latency by 14% through targeted performance improvements in the execution path.", "Designed LLM-based conversational agents and a multimodal RAG pipeline using LangChain, OpenAI, Qdrant, OCR, and CLIP.", "Designed an order-fulfillment pipeline that reduced processing failures by 78%, plus a serverless media pipeline on Lambda, S3, and FFmpeg."] },
  { role: "Associate Software Engineer", company: "Infospica", location: "Remote, India", timeframe: "Nov 2021 — Jun 2022", bullets: ["Built cross-platform React Native features for Android and iOS, integrating REST APIs and reusable production components."] },
];
const projects = [
  { name: "Happilee.io", tagline: "B2B customer engagement platform", description: "A business communication platform for WhatsApp engagement, AI-powered conversations, customer support, commerce, analytics, and deep third-party integrations.", stack: ["Node.js", "RabbitMQ", "LLMs", "Qdrant"], link: "https://happilee.io", ctaLabel: "View platform" },
  { name: "Distributed Notification Platform", tagline: "Reliable asynchronous delivery", description: "RabbitMQ-based email notification service with retries, dead-letter queues, scheduled delivery, idempotency, and Redis rate limiting.", stack: ["Node.js", "RabbitMQ", "Redis", "Docker"], link: "https://github.com/AdithyanKP/", ctaLabel: "View GitHub" },
  { name: "Appblocks", tagline: "Developer platform", description: "Backend components and APIs for standardized, reusable software blocks that accelerate consistent application development.", stack: ["Go", "APIs", "PostgreSQL", "Docker"], link: "https://www.appblocks.com/", ctaLabel: "Explore" },
];
const skillGroups = [["Backend & systems", "Node.js", "TypeScript", "Go", "PostgreSQL", "Redis", "RabbitMQ", "SQS", "REST APIs"], ["AI & search", "LangChain", "OpenAI", "LLMs", "AI agents", "RAG", "Qdrant", "OCR", "CLIP"], ["Cloud & delivery", "AWS", "Lambda", "EC2", "S3", "Docker", "Nginx", "CI/CD", "PM2"]];

export default function Home() {
  const [copied, setCopied] = useState("");
  const copyValue = async (value, label) => { await navigator.clipboard?.writeText(value); setCopied(label); setTimeout(() => setCopied(""), 1800); };
  return <main className={styles.page}>
    <div className={styles.ambient} />
    <nav className={styles.nav}><a href="#top" className={styles.wordmark}>AK<span>/</span>SYS</a><div><a href="#work">Work</a><a href="#stack">Stack</a><a href={resumePdf} download>Résumé ↓</a></div></nav>
    <section id="top" className={styles.hero}><div className={styles.heroCopy}><p className={styles.eyebrow}><i /> Backend engineer · distributed systems · AI</p><h1>Systems that <em>think</em>, scale, and keep moving.</h1><p className={styles.heroLead}>I’m Adithyan KP, a software engineer building event-driven backend systems and AI-powered product infrastructure. I care about reliable execution, useful intelligence, and measurable outcomes.</p><div className={styles.heroActions}><a className={styles.primaryCta} href="#work">See selected work <span>↘</span></a><a className={styles.secondaryCta} href="mailto:adithyankp777@gmail.com">Get in touch</a></div><div className={styles.socials}><IconButton aria-label="GitHub" onClick={() => window.open("https://github.com/AdithyanKP/")} className={styles.iconButton}><GitHubIcon /></IconButton><IconButton aria-label="LinkedIn" onClick={() => window.open("https://www.linkedin.com/in/adithyan-k-p/")} className={styles.iconButton}><LinkedInIcon /></IconButton></div></div><div className={styles.heroVisual}><div className={styles.systemLabel}>SYSTEMS / AI / 2026</div><img src={engineerArt} alt="Backend engineer working with distributed systems and AI" /><div className={styles.signal}><span className={styles.pulse} /> production signal<br /><b>10K+ daily interactions</b></div></div></section>
    <section className={styles.metrics}><div><strong>4+</strong><span>years engineering products</span></div><div><strong>300+</strong><span>businesses on workflow infrastructure</span></div><div><strong>78%</strong><span>reduction in fulfillment failures</span></div></section>
    <section id="work" className={styles.section}><header className={styles.sectionHeader}><p>01 / Production experience</p><h2>Build for the <em>real world.</em></h2></header><div className={styles.cardGrid}>{experience.map((item) => <article key={item.company} className={styles.card}><header><p className={styles.role}>{item.role}</p><h3>{item.company} <span>{item.location}</span></h3><p className={styles.timeframe}>{item.timeframe}</p></header><ul>{item.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul></article>)}</div></section>
    <section className={`${styles.section} ${styles.projectSection}`}><header className={styles.sectionHeader}><p>02 / Selected work</p><h2>From queues to <em>intelligence.</em></h2></header><div className={styles.projectGrid}>{projects.map((project, i) => <article key={project.name} className={styles.projectCard}><div className={styles.projectNumber}>0{i + 1}</div><p className={styles.role}>{project.name}</p><h3>{project.tagline}</h3><p>{project.description}</p><div className={styles.stack}>{project.stack.map((item) => <span key={item}>{item}</span>)}</div><a href={project.link} target="_blank" rel="noreferrer">{project.ctaLabel} <b>↗</b></a></article>)}</div></section>
    <section id="stack" className={styles.section}><header className={styles.sectionHeader}><p>03 / Technical focus</p><h2>The tools behind the <em>work.</em></h2></header><div className={styles.skillGrid}>{skillGroups.map(([title, ...items]) => <div key={title} className={styles.skillGroup}><p>{title}</p><div>{items.map((item) => <span key={item}>{item}</span>)}</div></div>)}</div></section>
    <section className={styles.contact}><p className={styles.eyebrow}><i /> Available for meaningful systems work</p><h2>Have a hard problem?<br /><em>Let’s make it move.</em></h2><div className={styles.contactActions}><a className={styles.primaryCta} href="mailto:adithyankp777@gmail.com">adithyankp777@gmail.com <span>↗</span></a><button onClick={() => copyValue("+916238531028", "phone")}>{copied === "phone" ? "Number copied" : "+91 62385 31028"}</button></div></section>
  </main>;
}
